Repository Arch881010/web-weather, pull requests merged in 2025-02, with the labels that each got.

#8 Update feature_request.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#10 feat: Add reflectivity bar to weather map settings panel
  docs/index.html
Labels: enhancement

#14 (Chore): Deploy only AFTER Github-actions updates the version
  .github/workflows/version.yaml
Labels: enhancement

#19 (Patch): Fix deployment
  .github/workflows/version.yaml
Labels: urgent

#21 Filtered out flood warnings and advisories
  docs/js/map.js
Labels: enhancement
